export const REQUEST_RUN_SUMMARY_DATA = 'REQUEST_DASHBOARD_DATA';
export const REQUEST_RUN_SUMMARY_DATA_FAILED = 'REQUEST_DASHBOARD_DATA_FAILED';
export const RECEIVE_RUN_SUMMARY_DATA = 'RECEIVE_DASHBOARD_DATA';

export const REQUEST_GRAPH_DATA = 'REQUEST_GRAPH_DATA';
export const REQUEST_GRAPH_DATA_FAILED = 'REQUEST_GRAPH_DATA_FAILED';
export const RECEIVE_GRAPH_DATA = 'RECEIVE_GRAPH_DATA';

export const REQUEST_DATASET = 'REQUEST_DATASET';
export const REQUEST_DATASET_FAILED = 'REQUEST_DATASET_FAILED';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';

export const CREATE_ENTRY = 'CREATE_ENTRY';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_FAILED = 'CREATE_ENTRY_FAILED';
