
export const ADD_ENTRY = 'ADD_ENTRY';
export const REQUEST_ENTRIES = 'REQUEST_ENTRIES';

export const REQUEST_RUN_SUMMARY_DATA = 'REQUEST_DASHBOARD_DATA';
export const REQUEST_RUN_SUMMARY_DATA_FAILED = 'REQUEST_DASHBOARD_DATA_FAILED';
export const RECEIVE_RUN_SUMMARY_DATA = 'RECEIVE_DASHBOARD_DATA';

export const REQUEST_GRAPH_DATA = 'REQUEST_GRAPH_DATA';
export const REQUEST_GRAPH_DATA_FAILED = 'REQUEST_GRAPH_DATA_FAILED';
export const RECEIVE_GRAPH_DATA = 'RECEIVE_GRAPH_DATA';
